CREATE TABLE IF NOT EXISTS `gsc_tip` (
	`id` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键',
	`tip_text` TINYINT(8) NOT NULL COMMENT 'tip的内容',
	PRIMARY KEY (`id`), INDEX `tip_text_idx` (`tip_text`)
) ENGINE=INNODB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8
